### ISSUE TITLE
add coverage support

### ISSUE THREAD

**Issue by sigmaSd** [impactaky/dax_extras#23]
I noticed that the coverage have decreased with these new methods, If you think adding coverage is a good idea (some ppl don't like it) then its simple to add:
- add these lines to deno.yml in github workflow
```yml
      - name: Create coverage report
        run: deno coverage ./coverage --lcov > coverage.lcov # create coverage report
      
      - name: Collect coverage
        uses: codecov/codecov-action@v1.0.10 # upload the report on Codecov
        with:
          file: ./coverage.lcov
```

then setup an account in https://about.codecov.io/
